"""add player_type and era columns

Revision ID: affc9bf53f72
Revises: 001
Create Date: 2026-01-15 01:15:57.474030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affc9bf53f72'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('coach_type', sa.String(length=50), nullable=True))
    op.add_column('coaches', sa.Column('era', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('player_type', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('era', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'era')
    op.drop_column('players', 'player_type')
    op.drop_column('coaches', 'era')
    op.drop_column('coaches', 'coach_type')
    # ### end Alembic commands ###
